- name: DÃ©ploiement du VNF Load Balancer
  hosts: localhost
  tasks:
    - name: Lancer le conteneur Load Balancer
      command: >
        docker run -d 
        --name vnf-lb 
        --network net-chain 
        -p 9090:80 
        -v /home/olivier/Documents/TP_Reseaux_Orchestration/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        haproxytech/haproxy-alpine