- name: DÃ©ploiement du VNF Firewall
  hosts: localhost
  tasks:
    - name: Lancer le conteneur Firewall (Relais TCP)
      command: >
        docker run -d 
        --name vnf-firewall 
        --network net-chain 
        -p 8080:8080 
        alpine/socat 
        TCP-LISTEN:8080,fork,bind=0.0.0.0 TCP:vnf-lb:80